name: 'Publish Pre-Release'
on:
  push:
    branches:
      - master

jobs:
  test:
    name: 'Run Tests'
    uses: ./.github/workflows/test.yml

  publish:
    name: 'Pre-release'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Configure Git'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Add Version'
        run: npm version prerelease

      - name: 'Publish'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
