name: 'Publish Pre-Release'
on:
  push:
    branches:
      - master

jobs:
  test:
    name: 'Run Tests'
    uses: ./.github/workflows/test.yml

  publish:
    name: 'Publish pre-release'
    uses: ./.github/workflows/release.yml
    with:
      version: prerelease
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
