name: 'Publish Pre-Release'
on:
  release:
    types:
      - published
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: 'Run Tests'
    uses: ./.github/workflows/test.yml

  publish:
    name: 'Publish package'
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
