name: 'Publish Pre-Release'
on:
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  test:
    name: 'Run Tests'
    uses: ./.github/workflows/test.yml

  publish:
    name: 'Publish package'
    needs: test
    uses: ./.github/workflows/release.yml
    if: github.ref == 'refs/head/master'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
