name: 'Release'
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: 'Release'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Configure Git'
        run: |
          git config user.name ${{ github.actor }}
          git config user.email github-actions@github.com

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Add Version'
        run: npm version ${{ inputs.version }}

      - name: 'Publish'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
