name: 'Tests'
run-name: '🧪 Test: ${{ github.event.head_commit.message || github.event.pull_request.title }}'
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened
  workflow_call:

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run tests'
        run: npm test